-- Création de la table CLIENT
CREATE TABLE CLIENT (
    ID_CLIENT INT PRIMARY KEY,
    NOM_CLIENT VARCHAR2(100) NOT NULL,
    ADRESSE_CLIENT VARCHAR2(200),
    TELEPHONE_CLIENT VARCHAR2(20)
);

-- Création de la table PRODUIT
CREATE TABLE PRODUIT (
    ID_PRODUIT INT PRIMARY KEY,
    NOM_PRODUIT VARCHAR2(100) NOT NULL,
    PRIX DECIMAL(10, 2) NOT NULL,
    STOCK INT NOT NULL
);

-- Création de la table COMMANDE
CREATE TABLE COMMANDE (
    ID_COMMANDE INT PRIMARY KEY,
    DATE_COMMANDE DATE NOT NULL,
    ID_CLIENT INT,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
);

-- Création de la table LIGNE_COMMANDE
CREATE TABLE LIGNE_COMMANDE (
    ID_LIGNE_COMMANDE INT PRIMARY KEY,
    ID_COMMANDE INT,
    ID_PRODUIT INT,
    QUANTITE INT NOT NULL,
    PRIX DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_COMMANDE) REFERENCES COMMANDE(ID_COMMANDE),
    FOREIGN KEY (ID_PRODUIT) REFERENCES PRODUIT(ID_PRODUIT)
);
